sudo: false

language: ruby
rvm:
- 2.6

cache: bundler

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # Required to avoid TLS errors

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

script:
  - set -e # Halt on any errors
  - bundle exec jekyll build # Build the website
  - bundle exec rake # Run the html-proofer tests
